# Generated by ariadne-codegen
# Source: ./gql/schema.gql

from enum import Enum


class OtpPurpose(str, Enum):
    VERIFY_ACCOUNT = "VERIFY_ACCOUNT"
    RESET_PASSWORD = "RESET_PASSWORD"


class TradingType(str, Enum):
    FUTURES = "FUTURES"
    SPOT = "SPOT"

class CEXExchanges(str, Enum):
    BINANCE = "BINANCE"
    MEXC = "MEXC"
    OKX = "OKX"
    ALL = "ALL"

class QueryMode(str, Enum):
    default = "default"
    insensitive = "insensitive"
