"use client";

// import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import Providers from "../components/providers";
import {Toaster} from "@/components/ui/toaster";
import {ScrollArea} from "@/components/ui/scroll-area";
// import Header from "@/app/home/components/header";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-theme="light" suppressHydrationWarning={true}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-screen flex flex-col box-border`}
            >
                <Providers>
                    <ScrollArea>
                        {/*<Header/>*/}
                        {children}
                        <Toaster />
                    </ScrollArea>
                </Providers>
            </body>
        </html>
    );
}
