image: docker:27.3

services:
  - docker:27.3-dind

variables:
  FRONTEND_IMAGE: frontend
  SERVER_IMAGE: server

stages:
    - build

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY_IMAGE -u $CI_REGISTRY_USER --password-stdin

build-backend:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script:
    - export VERSION=$(docker run --rm -v "$PWD":/app:ro -w /app node:slim node -p "require('./backend/package.json').version")
    - docker build -t $CI_REGISTRY_IMAGE/$SERVER_IMAGE:$VERSION ./backend
    - docker push $CI_REGISTRY_IMAGE/$SERVER_IMAGE:$VERSION


build-frontend:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  script:
    - export VERSION=$(docker run --rm -v "$PWD":/app:ro -w /app node:slim node -p "require('./frontend/package.json').version")
    - docker build -t $CI_REGISTRY_IMAGE/$FRONTEND_IMAGE:$VERSION ./frontend
    - docker push $CI_REGISTRY_IMAGE/$FRONTEND_IMAGE:$VERSION
