mutation CreateCryptoPortfolio($data: CreateCryptoPortfolioInput!) {
    createCryptoPortfolio(data: $data) {
        userId
    }
}

query GetCryptoPortfolios($data: GetCryptoPortfolioInput!, $timeFrame: String!) {
    getCryptoPortfolios(data: $data) {
        id
        exchanges
        tradingType
        investmentCategoryName
        latestHistoricalBalances(timeFrame: $timeFrame) {
            changeBalance
            changePercent
            estimatedBalance
        }
        balances {
            id
            balance
            assetInfo {
                id
                logo
                lastPrice
                symbol
            }
        }
    }
}

query GetHistoricalBalances($data: GetHistoricalBalanceInput!, $pagination: PaginationInput!) {
    getHistoricalBalances(data: $data, pagination: $pagination) {
        time
        estimatedBalance
        changePercent
        changeBalance
    }
}

query GetAsset($pagination: PaginationInput!, $getAssetPriceData: GetAssetPriceInput!, , $getAssetInfoData: GetAssetInfoInput!) {
    getAssetPrices(data: $getAssetPriceData, pagination: $pagination) {
        open_time
        openPrice
        closePrice
        highPrice
        lowPrice
    }
    getAssetInfo(data: $getAssetInfoData) {
        logo
        desc
        category
        symbol
        name
    }
}


subscription NewAssetPrice1m($data: GetAssetPriceInput!) {
    newAssetPrice1m (data: $data) {
        assetInfoId
        open_time
        openPrice
        closePrice
        highPrice
        lowPrice
    }
}

subscription NewAssetPrice5m($data: GetAssetPriceInput!) {
    newAssetPrice5m (data: $data) {
        assetInfoId
        open_time
        openPrice
        closePrice
        highPrice
        lowPrice
    }
}