mutation Signup($data: UserCreateInput!) {
    signup(data: $data) {
        accessToken
        refreshToken
    }
}

mutation Login($data: LoginReqDto!) {
    login(data: $data) {
        accessToken
    }
}

mutation VerifyAccount($data: VerifyDto!) {
    verifyAccount(data: $data) {
        accessToken
    }
}

query GetMe {
    getMe {
        email
        id
        name
        otp
        otpPurpose
    }
}

mutation CreateCryptoProfile($data: CreateCryptoProfileInput!) {
    createCryptoProfile(data: $data) {
        userId
    }
}

query GetCryptoProfile($data: GetCryptoProfileInput!) {
    getCryptoProfiles(data: $data) {
        profileId
        exchanges
        tradingType
        historicalBalances {
            time
            estimatedBalance
            changePercent
            changeBalance
        }
        balances {
            balance
            assetInfo {
                id
                logo
                lastPrice
                symbol
            }
        }
    }
}

query GetAsset($getAssetPriceData: GetAssetPriceInput!, $getAssetInfoData: GetAssetInfoInput!) {
    getAssetPrices(data: $getAssetPriceData) {
        open_time
        openPrice
        closePrice
        highPrice
        lowPrice
    }
    getAssetInfo(data: $getAssetInfoData) {
        logo
        desc
        category
        symbol
        name
    }
}


subscription NewAssetPrice1m($data: GetAssetPriceInput!) {
    newAssetPrice1m (data: $data) {
        assetInfoId
        open_time
        openPrice
        closePrice
        highPrice
        lowPrice
    }
}

subscription NewAssetPrice5m($data: GetAssetPriceInput!) {
    newAssetPrice5m (data: $data) {
        assetInfoId
        open_time
        openPrice
        closePrice
        highPrice
        lowPrice
    }
}
