query GetBank($userId: Int!) {
    getBankManagers(userId: $userId) {
        name
        createdAt
        updatedAt
        banks {
            name
            accountName
            accountNumber
            balance
            createdAt
            updatedAt
            historicalBalances {
                balance
                time
            }
            transactions {
                id
                bank {
                    name
                }
                amount
                spentAmount
                description
                createdAt
            }
        }
    }
}

query GetBankTransactions($userId: Float!) {
    getBankTransactions(userId: $userId) {
        id
        amount
        spentAmount
        createdAt
        description
        bank {
            name
        }
    }
}