# Generated by ariadne-codegen
# Source: ./gql/query.gql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetMe(BaseModel):
    get_me: "GetMeGetMe" = Field(alias="getMe")


class GetMeGetMe(BaseModel):
    email: str
    id: str
    name: Optional[str]


GetMe.model_rebuild()
