# Generated by ariadne-codegen
# Source: ./gql/query.gql

from pydantic import Field

from .base_model import BaseModel


class Signup(BaseModel):
    signup: "SignupSignup"


class SignupSignup(BaseModel):
    access_token: str = Field(alias="accessToken")
    refresh_token: str = Field(alias="refreshToken")


Signup.model_rebuild()
