# Generated by ariadne-codegen
# Source: ./gql/query.gql

from pydantic import Field

from .base_model import BaseModel


class VerifyAccount(BaseModel):
    verify_account: "VerifyAccountVerifyAccount" = Field(alias="verifyAccount")


class VerifyAccountVerifyAccount(BaseModel):
    access_token: str = Field(alias="accessToken")


VerifyAccount.model_rebuild()
