class TaskName:
    GET_CRYPTO_PORTFOLIO = "get_crypto_portfolio"
    ADD_NOT_EXISTED_ASSET_INFO = "add_not_existed_asset_info"
    GET_LATEST_PRICE = "get_latest_price"
    CONVERT_TO_PRICE_MAP = "convert_to_price_map"
    CONVERT_TO_ASSET_ID_MAP = "convert_to_asset_id_map"
    GET_LATEST_TIME = "get_latest_time"
    UPDATE_ASSET_BALANCES = "update_asset_balances"
    ADD_HISTORICAL_CRYPTO_BALANCE = "add_historical_crypto_balance"
    GET_BINANCE_ACCOUNT = "get_cex_account"
    UPDATE_CRYPTO_PORTFOLIO = "update_crypto_portfolio"
    ADD_HISTORICAL_ASSET_PROFITS = "add_historical_asset_profit"
    GET_LATEST_ASSET_PROFITS = "get_latest_asset_profits"
    GET_TRADES = "get_trades"