# queries and mutations for the expense category
query GetExpenseCategories($userId: Int!, $name: String, $startDate: DateTime, $endDate: DateTime, $month: Int, $year: Int) {
    getExpenseCategories(userId: $userId, name: $name) {
        color
        description
        name
        id
        countExpenses
        totalSpentAmounts(startDate: $startDate, endDate: $endDate) {
            amount
            month
            year
        }
        monthlyTargets(month: $month, year: $year) {
            month
            year
            target
        }
    }
}

mutation CreateExpenseCategory($data: CreateExpenseCategoryInput!) {
    createExpenseCategory(data: $data) {
        color
        description
        name
        id
    }
}

mutation UpdateExpenseCategory($id: String!, $data: UpdateExpenseCategoryInput!) {
    updateExpenseCategory(id: $id, data: $data) {
        color
        description
        name
        id
    }
}

mutation RemoveExpenseCategory($id: String!) {
    removeExpenseCategory(id: $id) {
        id
    }
}

query GetMonthlyTargets($categoryId: String!, $month: Int, $year: Int) {
    getMonthlyTargets(categoryId: $categoryId, month: $month, year: $year) {
        target
        month
        year
    }
}

mutation CreateMonthlyTarget($data: CreateMonthlyTargetInput!) {
    createMonthlyTarget(data: $data) {
        categoryId
    }
}

mutation UpdateMonthlyTarget($updateMonthlyTargetId: String!, $data: UpdateMonthlyTargetInput!) {
    updateMonthlyTarget(id: $updateMonthlyTargetId, data: $data) {
        categoryId
    }
}